services:
  postgres:
    image: postgres:17.3
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:2025-07-21-1
    container_name: pgadmin_container
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - app-network
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  springboot-dev:
    build: .
    container_name: springboot_dev
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
